### ISSUE TITLE
Prefers-accessibility Issues

### ISSUE THREAD

**Issue by jarieagito** [jarieagito/prefers-accessibility#1]
Hi there,

For some reason one of the perfers-accessibilities isn't working for Markbot. I've attached a screenshot below:
<img width="1415" alt="Screen Shot 2020-11-24 at 3 59 00 PM" src="https://user-images.githubusercontent.com/55108790/100150822-41ca7680-2e6e-11eb-8e88-6c5067cd85e4.png">

Thanks so much

@hellachella @JessJodoin

**Comment by JessJodoin** [comment]
Markbot is old and doesn't understand the prefers so you have to write them in the commented out section.

So move both your media tags (line 64 to line 82) between the `/* stylelint-disable media-feature-name-no-unknown */` and `/* stylelint-enable */`

Hope this helps 😄

**Comment by jarieagito** [comment]
Oh, I totally missed that part! Thank you very much
@JessJodoin
